### PR TITLE
repo: cleanup

### PR DESCRIPTION
**Pull request by vince-fugnitto**
**Description**

Fixes: https://github.com/eclipse-theia/theia-website/issues/312.
Closes: #310.

The pull-request cleans up the following:
- fixes misc typos
- updated `theiaPluginExcludeIds`
- removes references to the deprecated `@theia/python` extension
- removes deprecated documentation on `@theia/textmate-grammars`

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
The navigation points for language support are still visible and lead to an empty page:

image

I believe, given that the support has been dropped for quite some time now (2 years?), we can safely assume that we can just remove the files completely.

**Review by msujew — APPROVED** [review]
Looks good to me 👍

**Comment by vince-fugnitto** [comment]
@JonasHelming any objections?

**Comment by JonasHelming** [comment]
I am fine with the changes. One idea: Should we maybe add "Language Support" to the "Concepts/API" section and write 2-3 sentences that this topic is covered by the VS Code extension APi with a link to VS Code extensions in Theia and the language API of VS Code itself? People might look for this topic in the doc...

**Comment by vince-fugnitto** [comment]
> I am fine with the changes. One idea: Should we maybe add "Language Support" to the "Concepts/API" section and write 2-3 sentences that this topic is covered by the VS Code extension APi with a link to VS Code extensions in Theia and the language API of VS Code itself? People might look for this topic in the doc...

@JonasHelming if you provide the content I can add it as part of the pull-request, or you can add it later if you'd like.

**Review by JonasHelming — APPROVED** [review]

**Comment by JonasHelming** [comment]
Thank you for adding the additional page, looks great!

Your PR will add a new contributor to the start page as a side effect, so let's merge! :-)

**Pull request merged**
