### PR TITLE
Update dependencies and Node

### LINKED ISSUE #641: Update dependencies and Node

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #641

Everything should look as before, but the slider buttons are blue, as they are links.

### CODE REVIEW

**Comment by JonasHelming** [comment]
Do you have an idea why it tries to build with Node 14? I updated the workflows. It builds locally with Node 20

**Comment by jfaltermeier** [comment]
> Do you have an idea why it tries to build with Node 14? I updated the workflows. It builds locally with Node 20

I think this might be because the trigger is set to `pull_request_target`, which, as I understand it, runs the workflow from `master` rather than the updated one.

Temporarily changing it to `pull_request` might help to get a single test run with the updated workflow, though I’m not sure if there are any restrictions.

**Comment by jfaltermeier** [comment]
I noticed that when I resize the window to a smaller width, the sliders can overlap with the images:
ksnip_20241107-135916

**Comment by JonasHelming** [comment]
@jfaltermeier I also had to update the setup-node task, but now the build runs

**Comment by jfaltermeier** [comment]
> > I noticed that when I resize the window to a smaller width, the sliders can overlap with the images:
> > Yes, I personally find this acceptable. Alterntive would be to switch to show only two items earlier, which looks much weirder, IMHO

Fine by me. Once we switch back to `pull_request_target`, we can merge this.

**Comment by JonasHelming** [comment]
@jfaltermeier see latest commit, please re approve

**Review by jfaltermeier — APPROVED** [review]

**Pull request merged**
