### PR TITLE
Get adopters from eclipsefdn-project-adopters api

### PR DESCRIPTION
**Pull request by max-elia**
- Fetch adopters from api.eclipse.org/adopters/projects with project_id 'ecd.theia'
- Merge with manually added adopters (who are not yet present in API)
- Remove duplicates from resources and static data

Signed-off-by: Max Elia Schweigkofler <max_elia@hotmail.de>

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
I believe with this approach we lose the ordering we had which was based on history (ex: time when the company founded/adopted the project).

_currently_:

image


_pull-request_:

image

cc @JonasHelming I believe we should keep the ordering based on when they became adopters and not alphabetically, any thoughts? I addition, since there are still some entries in `data.js` we are alphabetical for a while, then we are not which looks even more incorrect.

**Comment by JonasHelming** [comment]
@vince-fugnitto : I would deprecate the order based on time and just go alphabetical. However, this should include the data.js entries. Is this fine for you @vince-fugnitto

**Comment by JonasHelming** [comment]
The main reason is indeed a technical one: we want to get rid of the adopter list in the theia website repository and use the external one (api.eclipse.org/adopters/projects) to avoid duplication. api.eclipse.org/adopters/projects does not provide order of appearance so we would need to track this information somehow separately. While I see the point of ordering by appearance, I wonder whether this is worth the effort.

**Comment by JonasHelming** [comment]
@vince-fugnitto Are you good with the proposal to sort everything alphabetically (so fixing the current bug)

**Comment by vince-fugnitto** [comment]
@JonasHelming it's a little unfortunate but I'm fine with it, I'm not sure what adopters think however.

**Comment by JonasHelming** [comment]
@max-elia Could you sort after merging the two lists then, please?

**Comment by max-elia** [comment]
The adopters are now being sorted after the ones added from this repo have been merged.

**Comment by JonasHelming** [comment]
thx! I will announce this in the next dev call and merge if there are no vetos

**Review by vince-fugnitto — APPROVED** [review]

**Pull request merged**
