### PR TITLE
Add Hackthon to banner

### LINKED ISSUE #365: Add Hackathon to website

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #365

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: 

I have feedback on the form itself however, we might want to add links for both "running theia from sources" and "signing the eca" as they might not be trivial for newcomers to discover for themselves.

**Comment by JonasHelming** [comment]
@vince-fugnitto : Thank you, but I am not sure what you mean. There are two links on the registration form. Do they not appear for you?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Thank you, but I am not sure what you mean. There are two links on the registration form. Do they not appear for you?

Sorry I see them, I think it was an issue where the page auto-scrolled to my email and I expected the details of ECA would be on the question itself. Everything seems fine :)

**Comment by JonasHelming** [comment]
That is on purpose :-)

**Pull request merged**
