### PR TITLE
Add 2023-01 community release plan

### LINKED ISSUE #357: Add 2023-01 community release

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #357

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Comment by JonasHelming** [comment]
@vince-fugnitto FYI

**Comment by JonasHelming** [comment]
@planger FYI, please align GLSP EMF.Cloud and CDT.cloud
@msujew FYI

**Comment by JonasHelming** [comment]
@jfaltermeier

**Review by msujew — APPROVED** [review]
LGMT 👍

**Pull request merged**
