### PR TITLE
Add terapines logo.

### PR DESCRIPTION
**Pull request by inlann**
We would like to be listed as a Theia Framework adopter. 😄 Sorry for sumbitting the failed PRs 😢

### CODE REVIEW

**Comment by JonasHelming** [comment]
Looks great, thank you!

**Comment by JonasHelming** [comment]
Please also add your entry here: https://ecdtools.eclipse.org/adopters/
We will eventually switch the Theia home page list to the https://ecdtools.eclipse.org/adopters/ list so we do not have to maintain this twice. To avoid loosing your entry, please add the one, too.

**Comment by inlann** [comment]
@JonasHelming  Hello, I already create a PR to (https://ecdtools.eclipse.org/adopters/)[https://ecdtools.eclipse.org/adopters/] at (here)[https://github.com/EclipseFdn/eclipsefdn-project-adopters/pull/173] 😄

**Comment by JonasHelming** [comment]
great, thanks, I will push to get the other PR merged

**Comment by inlann** [comment]
Thanks 😃

**Pull request merged**
