### PR TITLE
Add recent articles to resource section

### LINKED ISSUE #295: Add recent articles to resource section

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #295

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@JonasHelming are the significant changes due to formatting?

**Comment by JonasHelming** [comment]
Yeah, do not know what happened, the local diff was minimal, github shows all changes though. The commit adds 4 articles

**Comment by vince-fugnitto** [comment]
> Yeah, do not know what happened, the local diff was minimal, github shows all changes though. The commit adds 4 articles

@JonasHelming can you retry, it looks like there are leading whitespaces everywhere now:

image

**Review by vince-fugnitto — APPROVED** [review]
I updated the pull-request to have the minimal formatting changes required.
The changes look good to me, please squash before merging :+1:

**Comment by JonasHelming** [comment]
thanks @vince-fugnitto !

**Pull request merged**
