### PR TITLE
Updated footer

### PR DESCRIPTION
**Pull request by JonasHelming**
Changed copyright to Eclipse Foundation, added about link
see #154

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Comment by JonasHelming** [comment]
@spoenemann : Although the copy right is set to standard now, I want to make you aware of this change...

**Review by spoenemann — APPROVED** [review]
Thanks!

Just curious: why is the copyright to the EF? Isn't the website maintained by Theia committers?

**Comment by JonasHelming** [comment]
@brianking : Can you answer the question from above?

**Comment by brianking** [comment]
> Just curious: why is the copyright to the EF? Isn't the website maintained by Theia committers?

That requirement is defined here: https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

To ensure all web pages related to operation of the server use either the standard Eclipse.org footer template, or a footer that prominently contains a copyright notice, and the following set of links....

The requirement is that the page must contains a copyright notice.

An acknowledgement of project contributors / committers is optional, more a nice to have.

Projects can also define a Notice file, for example: https://github.com/EclipseFdn/react-eclipsefdn-members/blob/master/NOTICE.md

**Pull request merged**
